### **Basics of Quantum Information - 01**

In [1]:
import qiskit
import numpy as np
import sympy as sp
import pylatexenc
from qiskit import __version__
print(__version__)

2.2.1


#### **Vectors and Matrices in Pyhton**

In [2]:
ket0 = np.array([
    [1],
    [0]
])
ket1 = np.array([
    [0],
    [1]
])
print((ket0 + ket1)/2)

[[0.5]
 [0.5]]


In [3]:
# we can also built matrices using array
M1 = np.array([
    [2,4],
    [1,2]
])
M2 = np.array([
    [4,7],
    [9,1]
])
M = (M1 + M2) / 2
print(M)

[[3.  5.5]
 [5.  1.5]]


In [4]:
# matrix multiplication
print(np.matmul(M1,M2))
print(np.matmul(M,M2))
print(np.matmul(M1,ket0))

[[44 18]
 [22  9]]
[[61.5 26.5]
 [33.5 36.5]]
[[2]
 [1]]


In [5]:
# How we can dislay matrices in a nicer way
from qiskit.visualization import array_to_latex 
display(array_to_latex(np.matmul(M,M2)))

<IPython.core.display.Latex object>

#### **States, Measurements, and operations**

In [16]:
# Define and display state vectors
from qiskit.quantum_info import Statevector
psi = Statevector([1/2, 1/2, 1/2,1/2])
chi = Statevector([(1+3j)/2 , -2/3])
display(psi.draw('latex'))
display(psi.draw('text'))
display(psi.draw('latex_source'))
# The Statevector class also have an option `is_valid` which cheks that whether the given state is valid quantum state or not!

display(psi.is_valid())

<IPython.core.display.Latex object>

[0.5+0.j,0.5+0.j,0.5+0.j,0.5+0.j]

'\\frac{1}{2} |00\\rangle+\\frac{1}{2} |01\\rangle+\\frac{1}{2} |10\\rangle+\\frac{1}{2} |11\\rangle'

True

#### **Simulating measurements using Statevector**

In [17]:
display(chi.draw('latex'))

<IPython.core.display.Latex object>

In [29]:
outcome, state = psi.measure()
print(outcome, state)

00 Statevector([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
            dims=(2, 2))
